### ISSUE TITLE
Error: weights must be 2D

### ISSUE THREAD

**Issue by arunksagotra** [iLampard/ep_llm#1]
Hi,

Thanks for the code. I am trying to run the code for gdelt data. I am getting an error. I have added the screen shot of the error. 
![error](https://github.com/iLampard/lamp/assets/145635480/c7ea17f5-a18e-43a7-90f5-e2a57dc4d403)

**Comment by s2014628** [comment]
i have faced the same issue darling pls help

**Comment by iLampard** [comment]
Hi, 

what's your torch version?  

you should use 1.x version instead of 2.0.

**Comment by Maple728** [comment]
We will fix the compatibility issue with the torch version (1.x and 2.x) as soon as possible.

**Comment by iLampard** [comment]
@s2014628 @arunksagotra  the compatibility issue has been fixed in the master branch
