### ISSUE TITLE
Handling Duplicate Time Sequences in GDELT Dataset

### ISSUE THREAD

**Issue by eogns282** [iLampard/ep_llm#5]
Hi,

Thank you for sharing your interesting research. While examining GDELT data you uploaded, I noticed numerous duplicate entries in time sequences. Could you clarify how these duplicates are processed within your TPP models? Understanding your approach to handling these repetitions would be incredibly helpful for my research.

Thank you.

**Comment by iLampard** [comment]
Hi, 

if i remember correctly, duplicate entries are treated as normal input into the model. for details of the computation, you can have a look at the KnowEvolve paper, we simply follow it to compute the intensities.

**Comment by eogns282** [comment]
Dooray! Failure Notice



  
  
    
    
  
  
    
        Failure Notice
    
  
  
    
        
        Your message sent to
          
***@***.***) 
          has failed to be delivered.
        
        
          Please refer to the below for details.
        
    
  
  
    
      
        
          
            * Recipient : 
***@***.***) 
          
          
            * Sent time : 
2024-03-20T23:13:45
          
          
            * Subject : 
Re: [iLampard/lamp] Handling Duplicate Time Sequences in GDELT Dataset (Issue #5)
          
          
            
              
                * Remote host said : 
              
              
                
Your mail was denied from the receiver.
                
              
            
                      
          
        
      
    
  
  
    
        
          This message was sent from a notification-only address that cannot accept incoming email.
          For more information, please contact           ***@***.***
        
    
  
  
    
        © Dooray!.
