### ISSUE TITLE
Model Details about KnowEvolveANHP

### ISSUE THREAD

**Issue by yesluck** [iLampard/ep_llm#7]
Hi Team, 
 
Thank you so much for sharing this amazing framework for event prediction! 
 
When I am trying to go through your code, I see you are using the class "`KnowEvolveANHP`" to train the base event sequence model. From your paper, I saw you mentioned both KE and ANHP are state-of-the-art event sequence models. So I wish to understand if `KnowEvolveANHP` is a combination of these two models, or what the relationship is between the implementation of `KnowEvolveANHP` and these SOTA event sequence models. 
  
Thanks a lot for your time and consideration!

**Comment by iLampard** [comment]
Hi,

Yes, KnowEvolveANHP is a combination of the two models, which simply refers to add attention structure to the original KnowEvolve model.

**Comment by yesluck** [comment]
Thanks a lot, Team. This helps a lot!
